---
- name: Clone simp_le
  git:
    repo="{{simp_le_repo}}"
    version="{{simp_le_version}}"
    dest="{{simp_le_dest}}"
  register: git

# Duplicate bootstrap.sh behavior.
- name: Install dependencies.
  become: yes
  apt:
    name="{{item}}"
    cache_valid_time="86400"
    update_cache=yes
  with_items: "{{simp_le_dependencies}}"

# If the git repo has changed we need to rebuild the venv
- name: nuke the venv
  file:
    state=absent
    path="{{simp_le_dest}}/venv"
  when: git.changed

- name: make venv dir
  file:
    state=directory
    path="{{simp_le_dest}}/venv"
  when: git.changed

# Duplicate venv.sh behavior.
- name: Setup venv.
  pip:
    virtualenv="{{simp_le_dest}}/venv"
    name="{{item}}"
    chdir="{{simp_le_dest}}"
    state=latest
    virtualenv_python="python3"
  with_items: "{{simp_le_python_dependencies}}"

- name: Setup simp_le.
  pip:
    virtualenv="{{simp_le_dest}}/venv"
    name="{{simp_le_dest}}"
    chdir="{{simp_le_dest}}"
